GET http://localhost:3333/games/46b31757-30ee-45c7-954a-2443d4600608/ads

###
GET http://localhost:3333/games

###
GET http://localhost:3333/ads/408db121-ef53-4fa1-a5a3-09ac409b83fd/discord

###
POST http://localhost:3333/games/e3a94c17-7f69-46da-9e1e-75946cc27856/ads
Content-Type: application/json

{
    "name": "Jorge Amado",
    "yearsPlaying": 3,
    "discord": "amadinho",
    "weekDays": [
        1,
        3,
        6
    ],
    "hoursStart": "1:00",
    "hoursEnd": "6:33",
    "useVoiceChannel": true
}
